Test with python 3.12 and 3.13 and use 3.13 for the other github actions
MatthewFlamm/pytest-homeassistant-custom-component pull request #205
Opened 2024-11-28 08:47 UTC by jwillemsen

* .devcontainer/devcontainer.json:
    * .github/workflows/automatic_generation.yml:
    * .github/workflows/generate_package.yml:
    * .github/workflows/make_release.yml:
    * .github/workflows/publish.yml:
    * .github/workflows/pytest.yml:
    * setup.py:

2024-11-28 15:52 UTC, brianegge approved these changes

2024-11-29 03:17 UTC, MatthewFlamm requested changes

2024-11-29 03:17 UTC, MatthewFlamm commented on setup.py
> +    python_requires=">=3.13",
From my reading, homeassistant still supports 3.12 and still tests against it 

See

https://github.com/home-assistant/core/blob/24f7bae5f260c7b4417e0b21d4f742ca916b2349/pyproject.toml#L25

https://github.com/home-assistant/core/blob/24f7bae5f260c7b4417e0b21d4f742ca916b2349/.github/workflows/ci.yaml#L45

2024-11-29 03:17 UTC, MatthewFlamm commented on .github/workflows/pytest.yml
> +        python-version: ["3.13"]
We should test against 3.12 and 3.13

2024-11-29 03:17 UTC, MatthewFlamm commented on .github/workflows/automatic_generation.yml
> +        python-version: ['3.13']
We should test against 3.12 and 3.13

2024-11-29 15:20 UTC, MatthewFlamm approved these changes
Thanks!

2024-11-29 15:20 UTC, merged